goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../codemirror.inc.js", ['cljsjs.codemirror'], []);
goog.addDependency("../clojure.inc.js", ['cljsjs.codemirror.mode.clojure'], ['cljsjs.codemirror']);
goog.addDependency("../xml.inc.js", ['cljsjs.codemirror.mode.xml'], ['cljsjs.codemirror']);
goog.addDependency("../matchbrackets.inc.js", ['cljsjs.codemirror.addon.edit.matchbrackets'], ['cljsjs.codemirror']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../clojure/zip.js", ['clojure.zip'], ['cljs.core']);
goog.addDependency("../hickory/utils.js", ['hickory.utils'], ['goog.string', 'cljs.core', 'clojure.string']);
goog.addDependency("../hickory/core.js", ['hickory.core'], ['clojure.zip', 'goog.string', 'cljs.core', 'hickory.utils']);
goog.addDependency("../closebrackets.inc.js", ['cljsjs.codemirror.addon.edit.closebrackets'], ['cljsjs.codemirror']);
goog.addDependency("../closetag.inc.js", ['cljsjs.codemirror.addon.edit.closetag'], ['cljsjs.codemirror']);
goog.addDependency("../html2hiccup/core.js", ['html2hiccup.core'], ['cljs.core', 'cljsjs.codemirror', 'cljsjs.codemirror.mode.clojure', 'cljsjs.codemirror.mode.xml', 'cljsjs.codemirror.addon.edit.matchbrackets', 'clojure.string', 'hickory.core', 'cljsjs.codemirror.addon.edit.closebrackets', 'cljsjs.codemirror.addon.edit.closetag']);
